#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

task main()
{
	while(true){
		getJoystickSettings(joystick);
		motor[leftMotor] = joystick.joy1_y1*100.0/128.0;
		motor[rightMotor] = joystick.joy1_y2*100.0/128.0;
	}
}
