#pragma config(Sensor, S1,     color,          sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Logger.h"

task main()
{
	string fileName = "LogTest.txt";
	int fileSize = 1000;
	TFileHandle fileHandle;
	TFileIOResult IOResult;
	string one = "Yay!\n";
	string two = "It works!";

	Logger_Start(fileName, fileSize, fileHandle, IOResult);
	Logger_WriteString(fileHandle, IOResult, one);
	Logger_WriteString(fileHandle, IOResult, two);
	Logger_Close(fileHandle, IOResult);
}
